name: weather
description: A weather app to display selected regions weather

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  introduction_screen: ^1.0.7
  cupertino_icons: ^0.1.3
  http: 0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - images/night.png

  fonts:
    - family:  Weather
      fonts:
        - asset: fonts/Weather.ttf
